//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarPool
    {
        public long CarPoolID { get; set; }
        public long TripID { get; set; }
        public string Email { get; set; }
        public string StartingLocation { get; set; }
        public string EndLocation { get; set; }
    }
}
