//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class CarpoolEntities : DbContext
    {
        public CarpoolEntities()
            : base("name=CarpoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CarPool> CarPools { get; set; }
        public DbSet<Trip> Trip { get; set; }
    
        public virtual int CreateTrip(string emailAddress, string startingLocation, string endLocation, string dateOfDeparture, string timeOfDeparture, string maxDeviation)
        {
            var emailAddressParameter = emailAddress != null ?
                new ObjectParameter("EmailAddress", emailAddress) :
                new ObjectParameter("EmailAddress", typeof(string));
    
            var startingLocationParameter = startingLocation != null ?
                new ObjectParameter("StartingLocation", startingLocation) :
                new ObjectParameter("StartingLocation", typeof(string));
    
            var endLocationParameter = endLocation != null ?
                new ObjectParameter("EndLocation", endLocation) :
                new ObjectParameter("EndLocation", typeof(string));
    
            var dateOfDepartureParameter = dateOfDeparture != null ?
                new ObjectParameter("DateOfDeparture", dateOfDeparture) :
                new ObjectParameter("DateOfDeparture", typeof(string));
    
            var timeOfDepartureParameter = timeOfDeparture != null ?
                new ObjectParameter("TimeOfDeparture", timeOfDeparture) :
                new ObjectParameter("TimeOfDeparture", typeof(string));
    
            var maxDeviationParameter = maxDeviation != null ?
                new ObjectParameter("MaxDeviation", maxDeviation) :
                new ObjectParameter("MaxDeviation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateTrip", emailAddressParameter, startingLocationParameter, endLocationParameter, dateOfDepartureParameter, timeOfDepartureParameter, maxDeviationParameter);
        }
    }
}
